### ISSUE TITLE
（暂时解决）Status Error

### ISSUE THREAD

**Issue by jyeric** [ZJUGuoShuai/img-paste#6]
![捕获4.png](https://i.loli.net/2019/05/22/5ce4cea9e6f5196931.png)
可以通过sm.ms正常上传。但是无法通过https://zjuguoshuai.github.io/img-paste/ 上传

**Comment by ZJUGuoShuai** [comment]
抱歉，这个问题确实是，现在还没找到出错的原因，希望有能力的同学帮忙看一下

**Comment by jyeric** [comment]
现在有莫名其妙的好了？
莫非是sm.ms的api不稳定还是怎么的
![](https://i.loli.net/2019/06/27/5d14b5f7047b531280.png)

**Comment by jyeric** [comment]
先进行关闭，如果仍有问题再重开
